services:
  node-app:
    container_name: express-app
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run dev
# this is the docker-compose.dev.yml file
